test_scenarios:
  - name: "1/2/4/8k input-1k output"
    description: "Balanced test with 1k input and 1k output tokens"
    request_rate: 0  # inf
    concurrency: [1, 2, 4, 8, 16, 32, 48, 64, 80, 96, 112, 128, 192, 256]
    input_length: [1024, 2048, 4096, 8192]
    output_length: 1024
    num_iteration: 8
